name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: mskelton/setup-yarn@3c5d9b1e9b3fef69d05b4968efb613594da89f87 # v1
        with:
          node-version: "18.x"

      - name: Run ESLint
        run: yarn lint
