name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: mskelton/setup-yarn@15308d4b4c6e3e3ee269ec97a91d0d6bbb24ff36 # v2
        with:
          node-version: "18.x"

      - name: Run ESLint
        run: yarn lint
